site_name: Tôi luyện Tiếng Anh - Khu học mở. 
site_description: Tự học Tiếng Anh các kiểu, chắc vậy.
site_author: duykhanh471  
site_url: https://daihocmo.github.io/tieng-anh/

nav:
  - 'Trang chủ': 
    - 'Trang chủ': 'index.md'
    - 'Tham gia cộng đồng học': 'cong-dong.md'
  - 'Hướng dẫn':
    - 'Tự học Tiếng Anh': 'guide.md'
    - '30 Ngày Tiếng Anh': '30ngay.md'
    - 'Nói Tiếng Anh': 'speaking.md'
    - 'Đọc Tiếng Anh': 'reading.md'
    - 'Hướng dẫn đơn ngữ': 'monolingual.md'
    - 'FAQ về Tiếng Anh': 'faq.md'
  - 'Cài đặt':  
    - 'Mining': 'setup.md'
    - 'Goldendict': 'goldendict.md'
  - 'Tài nguyên học':
    - 'Tài nguyên': 'resources.md'
    - 'Comprehensible Input': 'input.md'
  - 'Những thứ khác':
    - 'Có gì hay?': 'misc.md'
    - 'Input Hypothesis': 'input.md'

      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - search.highlighting
    - search.share
    - search.suggest
  name: material
  
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
plugins:
  - search
  - open-in-new-tab

extra:
  generator: false